version: "3.6"
services:
  dynamic:
    build: ./dynamic
    ports:
      - "8080:8080"
    networks:
      - frontend
    deploy:
      replicas: 1
    environment:
      - VIRTUAL_HOST=dynamic

  static:
    build: ./static/
    depends_on:
      - dynamic
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=static      
    networks:
      - frontend

networks:
  frontend:
