version: "3.6"
services:
  dynamic:
    build: ./dynamic
    ports:
      - "8080"
    networks:
      - frontend
    deploy:
      replicas: 1
    restart_policy:
      condition: on-failure

  static:
    build: ./static/
    depends_on:
      - dynamic
    ports:
      - "80"
    networks:
      - frontend

networks:
  frontend:
